"""initial migration

Revision ID: 166d3f76dd5b
Revises: 
Create Date: 2026-02-04 21:45:54.317573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '166d3f76dd5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add NEW Tables (OTP & Social Interactions)
    op.create_table('user_otps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('otp_code', sa.String(length=6), nullable=True),
        sa.Column('purpose', sa.String(length=20), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('social_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_comments_id'), 'social_comments', ['id'], unique=False)

    op.create_table('social_likes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_likes_id'), 'social_likes', ['id'], unique=False)

    # 2. UPDATE Existing Tables (Don't DROP them!)
    # We add columns that might be missing in Python but exist in SQL
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_users_firebase_uid', 'users', ['firebase_uid'])
    
    # 3. Handle the Geometry Column specifically
    # We keep the decimal columns as backup/helpers but DO NOT drop 'location'
    op.add_column('profiles', sa.Column('location_lat', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('profiles', sa.Column('location_long', sa.Numeric(precision=11, scale=8), nullable=True))

    # 4. Message Routing fix
    op.add_column('messages', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_messages_recipient', 'messages', 'users', ['recipient_id'], ['id'])

    # 5. Clean up Followers logic
    op.create_unique_constraint('_follower_following_uc', 'followers', ['follower_id', 'following_id'])
    
    
    
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.ENUM('user', 'admin', 'moderator'), server_default=sa.text("'user'"), nullable=True))
    op.add_column('users', sa.Column('last_login', mysql.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_auth_status'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'firebase_uid')
    op.drop_index(op.f('ix_swipes_id'), table_name='swipes')
    op.drop_index('idx_swiper_target', table_name='swipes')
    op.create_index(op.f('idx_prevent_duplicate_swipe'), 'swipes', ['swiper_id', 'target_id'], unique=True)
    op.create_index(op.f('idx_mutual_match_check'), 'swipes', ['target_id', 'swiper_id', 'swipe_type'], unique=False)
    op.alter_column('swipes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('swipes', 'swipe_type',
               existing_type=sa.Enum('like', 'dislike', 'super_like', name='swipetype'),
               type_=mysql.ENUM('like', 'dislike', 'super-like'),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('location', sa.NullType(), nullable=False))
    op.add_column('profiles', sa.Column('cover_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.create_index(op.f('username'), 'profiles', ['username'], unique=True)
    op.create_index(op.f('idx_spatial_location'), 'profiles', ['location'], unique=False, mysql_prefix='SPATIAL')
    op.create_index(op.f('idx_search_profile'), 'profiles', ['username', 'full_name'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('profiles', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('profiles', 'gender',
               existing_type=sa.Enum('male', 'female', 'non_binary', 'other', name='gender'),
               type_=mysql.ENUM('male', 'female', 'non-binary', 'other'),
               existing_nullable=True)
    op.drop_column('profiles', 'location_long')
    op.drop_column('profiles', 'location_lat')
    op.add_column('posts', sa.Column('status', mysql.ENUM('active', 'archived', 'flagged'), server_default=sa.text("'active'"), nullable=True))
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index(op.f('idx_feed_retrieval'), 'posts', ['user_id', 'status', 'created_at'], unique=False)
    op.alter_column('posts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('posts', 'thumbnail_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('posts', 'media_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_ibfk_2'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('idx_room_history'), 'messages', ['room_id', 'created_at'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('messages', 'recipient_id')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.create_index(op.f('idx_unique_match'), 'matches', ['user_one', 'user_two'], unique=True)
    op.alter_column('matches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('_follower_following_uc', 'followers', type_='unique')
    op.create_index(op.f('idx_following_lookup'), 'followers', ['following_id'], unique=False)
    op.alter_column('followers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('followers', 'id')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(op.f('chat_rooms_ibfk_1'), 'chat_rooms', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.alter_column('chat_rooms', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('post_interactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('like', 'save', 'share'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_interactions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_interactions_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('post_id'), 'post_interactions', ['post_id', 'user_id', 'type'], unique=True)
    op.create_table('interests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('name'), 'interests', ['name'], unique=True)
    op.create_table('reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'reviewed', 'resolved', 'ignored'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('reports_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interests',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('user_interests_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_interests_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('match', 'message', 'follow', 'like'), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_user_unread'), 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_table('dating_preferences',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interested_in', mysql.ENUM('male', 'female', 'everyone'), server_default=sa.text("'everyone'"), nullable=True),
    sa.Column('min_age', mysql.INTEGER(), server_default=sa.text("'18'"), autoincrement=False, nullable=True),
    sa.Column('max_age', mysql.INTEGER(), server_default=sa.text("'100'"), autoincrement=False, nullable=True),
    sa.Column('max_distance_km', mysql.INTEGER(), server_default=sa.text("'50'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('dating_preferences_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('push_notifications', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('ghost_mode', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('show_distance', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_settings_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_social_likes_id'), table_name='social_likes')
    op.drop_table('social_likes')
    op.drop_index(op.f('ix_social_comments_id'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_table('user_otps')
    # ### end Alembic commands ###
